CREATE TABLE IF NOT EXISTS PUBLIC.EXAMPLE (
	ID CHARACTER VARYING(19) NOT NULL,
	CREATED_BY CHARACTER VARYING(19),
	CREATED_AT TIMESTAMP,
	UPDATED_BY CHARACTER VARYING(19),
	UPDATED_AT TIMESTAMP,
	VERSION INTEGER,
	TEST CHARACTER(255),
	CONSTRAINT EXAMPLE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_4F ON PUBLIC.EXAMPLE (ID);