spring:
  application:
    name: easycrud-example
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./testdb/easycrud;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;INIT=RUNSCRIPT FROM 'classpath:sql/init.sql'
    platform: h2
    username: username
    password: password
    jpa:
#      database-platform: org.hibernate.dialect.H2Dialect
      database-platform: org.hibernate.dialect.Oracle12cDialect
      show-sql: true
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8080

server:
  port: 8100
  servlet:
    context-path: /easycrud-example

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  info:
    env:
      enabled: true
  security:
    enabled: false
  loggers:
    enabled: true

custom:
  cache:
    engine: Caffeine
