name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and install parent project
      run: |
        cd easycrud-parent
        mvn -B install --file pom.xml
    - name: Build and install core project
      run: |
        cd easycrud-core
        mvn -B install --file pom.xml
    - name: Build example project
      run: |
        cd easycrud-example
        mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Generate dependency graph for parent project
      run: |
        cd easycrud-parent
        mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
    
    - name: Generate dependency graph for core project
      run: |
        cd easycrud-core
        mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
    
    - name: Generate dependency graph for example project
      run: |
        cd easycrud-example
        mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph

